config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'banks#index'

  resources :banks do
    resources :transactions
  end

  #route for sum of transaction for given bank
  get 'banks/:id/sum', to: 'banks#transactionTotal'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
    has_many :transactions, dependent: :destroy
    validates :name, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :bank
  validates :amount, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
    def index
        @banks = Bank.all
    end

    def show
        @bank = getBankById
    end

    def new
        @bank = Bank.new
    end

    def create
        @bank = Bank.new(parameters)
        if @bank.save
          redirect_to @bank
        else
          render 'new'
        end
    end

    def edit
        @bank = getBankById
    end

    def update
        @bank = getBankById
        if @bank.update(parameters)
            redirect_to @bank
        else
            render 'edit'
        end
    end

    def destroy
        @bank = getBankById
        @bank.destroy
        redirect_to banks_path
    end

    def transactionTotal
        @total = getBankById.transactions.sum(:amount)
    end
    
    private
    def getBankById
        Bank.find(params[:id])
    end
    def parameters
        params.require(:bank).permit(:name)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def new
        @transaction = findBankById.transactions.build
    end
    
    def create
        @bank = findBankById
        @transaction =  @bank.transactions.create(parameters)
        if @transaction.save
            redirect_to bank_path(@bank)
        else
            render 'new'
        end
    end

    def destroy
        @transaction, @bank = findTransactionByIds
        @transaction.destroy

        redirect_to bank_path(@bank)
    end

    def edit
        @transaction, @bank = findTransactionByIds
    end

    def update
        @transaction, @bank = findTransactionByIds
        if (@transaction.update(parameters))
            redirect_to bank_path(@bank)
        else
            render 'edit'
        end
    end

    private
    def findBankById
        Bank.find(params[:bank_id])
    end

    def findTransactionByIds
        bank = findBankById
        return bank.transactions.find(params[:id]), bank
    end

    def parameters
        params.require(:transaction).permit(:amount, :date, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/banks/_bank.html.erb
<tr>
    <td><%= bank.name %></td>
    <td><%= bank.transactions.count() %></td>
    <td><%= bank.transactions.sum(:amount) %></td>
    <td>
    <% transaction = bank.transactions.order(:date).last %>
    <% if transaction %>
        <%= transaction.date%>
    <%end%>
    </td>
    <% if @showControls %>
        <td><%= link_to 'Show', bank_path(bank) %></td>
        <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
        <td><%= link_to 'Delete', bank_path(bank), method: :delete %></td>
    <%end%>
</tr>

app/views/banks/_errors.html.erb
<% if @bank.errors.any? %>
    <div class="errorExplanation">
      <span class="errorHeader">
        <%= pluralize(@bank.errors.count, "error") %> when creating bank
      </span>
      <ul>
        <% @bank.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/banks/_form.html.erb
<%= form_with(model: @bank, local: true) do |form| %>

    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <%= form.submit %>

<% end %>

app/views/banks/_tableHeader.html.erb
<tr>
    <th>Name</th>
    <th>number of transactions</th>
    <th>sum of transactions</th>
    <th>date of last transaction</th>
    <% if @showControls %>
        <th colspan="3"></th>
    <% end %>
</tr>

app/views/banks/edit.html.erb
<h1>Edit Bank</h1>
<%= render 'errors' %>
<%= render 'form' %> 
<%= link_to 'Back', banks_path %>

app/views/banks/index.html.erb
<h1>List of all banks</h1>
<table>
<% @showControls = true %>
<%= render 'tableHeader' %>
<%= render @banks%>
</table>
<%= link_to 'New bank', new_bank_path %>

app/views/banks/new.html.erb
<h1>Create New Bank</h1>
<%= render 'errors'%>
<%= render 'form' %>
<%= link_to 'Back', banks_path %>

app/views/banks/show.html.erb
<h1> Bank <%= @bank.name %> </h1>

<table>
<% @showControls = false %>
<%= render 'tableHeader'%>
<%= render @bank%>
</table>

<table>
<h2>Transactions :</h2>
<%= render 'transactions/tableHeader' %> 
<%= render @bank.transactions.order(:date).reverse_order %>
</table>
<span style="font-weight:bold">Transaction Sum : </span>
<%= @bank.transactions.sum(:amount) %>
<br>
<%= link_to 'New Transaction' , new_bank_transaction_path(bank_id: @bank.id)%>
<br>
<%= link_to "Back", banks_path %>

app/views/banks/transactionTotal.html.erb
<%= @total %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/_errors.html.erb
<% if @transaction.errors.any? %>
    <div class="errorExplanation">
      <span class="errorHeader">
        <%= pluralize(@transaction.errors.count, "error") %> when creating transaction
      </span>
      <ul>
        <% @transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/transactions/_form.html.erb
<%= form_with(model: [ @transaction.bank, @transaction ], local: true) do |form| %>

    <%= form.label(:date) %>
    <%= form.datetime_local_field(:date) %>
    <%= form.label(:amount) %>
    <%= form.number_field(:amount, :step => 0.01) %>
    <%= form.label(:description) %>
    <%= form.text_area(:description) %>
    <%= form.submit%>
    
<% end %>

app/views/transactions/_tableHeader.html.erb
<tr>
    <th>Date</th>
    <th>Amount</th>
    <th>Description</th>
    <th colspan="2"></th>
</tr>

app/views/transactions/_transaction.html.erb
<tr>
    <td><%= transaction.date %></td>
    <td><%= transaction.amount %></td>
    <td><%= transaction.description %></td>
    <td><%= link_to "Delete", [transaction.bank, transaction], method: :delete %></td>
    <td><%= link_to "Edit", edit_bank_transaction_path(transaction.bank, transaction) %></td>
</tr>

app/views/transactions/edit.html.erb
<h1>Edit Transaction</h1>
<%= render 'errors' %>
<%= render 'form' %>
<%= link_to 'Back', bank_path(@transaction.bank) %>

app/views/transactions/new.html.erb
<h1>Create New Transaction</h1>
<%= render 'errors' %>
<%= render 'form' %>
<%= link_to 'Back', bank_path(@transaction.bank) %>